package com.example.aipoweredtravelplanner.data.model.response

import com.example.aipoweredtravelplanner.data.model.Content

/**
 * The response model from the Gemini API.
 * This holds the list of possible answers (candidates) the Gemini model generated.
 *
 * @property candidates The list of [Candidate] answers from Gemini.
 */
data class GeminiResponse(
    val candidates: List<Candidate>
)

/**
 * A single response option generated by the model.
 *
 * @property content The content of this response (e.g., text, images).
 */
data class Candidate(
    val content: Content
)